// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// EmployeeDao is the data access object for table employee.
type EmployeeDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns EmployeeColumns // columns contains all the column names of Table for convenient usage.
}

// EmployeeColumns defines and stores column names for table employee.
type EmployeeColumns struct {
	Id           string // 员工ID
	EmployeeName string // 员工名称
	Age          string // 员工年纪
	DepartmentId string // 员工部门ID
}

// employeeColumns holds the columns for table employee.
var employeeColumns = EmployeeColumns{
	Id:           "id",
	EmployeeName: "employee_name",
	Age:          "age",
	DepartmentId: "department_id",
}

// NewEmployeeDao creates and returns a new DAO object for table data access.
func NewEmployeeDao() *EmployeeDao {
	return &EmployeeDao{
		group:   "default",
		table:   "employee",
		columns: employeeColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *EmployeeDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *EmployeeDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *EmployeeDao) Columns() EmployeeColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *EmployeeDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *EmployeeDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *EmployeeDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
