// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"gf_crud/internal/model"
)

type (
	IDepartment interface {
		Test(ctx context.Context, input model.DepartmentInput) (output *model.DepartmentOutput, err error)
	}
)

var (
	localDepartment IDepartment
)

func Department() IDepartment {
	if localDepartment == nil {
		panic("implement not found for interface IDepartment, forgot register?")
	}
	return localDepartment
}

func RegisterDepartment(i IDepartment) {
	localDepartment = i
}
