// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_crud/internal/dao/internal"
)

// internalDepartmentDao is internal type for wrapping internal DAO implements.
type internalDepartmentDao = *internal.DepartmentDao

// departmentDao is the data access object for table department.
// You can define custom methods on it to extend its functionality as you wish.
type departmentDao struct {
	internalDepartmentDao
}

var (
	// Department is globally public accessible object for table department operations.
	Department = departmentDao{
		internal.NewDepartmentDao(),
	}
)

// Fill with you ideas below.
