// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Department is the golang structure for table department.
type Department struct {
	Id             int    `json:"id"             description:"部门ID"`
	DepartmentName string `json:"departmentName" description:"部门名称"`
}
