// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Employee is the golang structure for table employee.
type Employee struct {
	Id           int    `json:"id"           description:"员工ID"`
	EmployeeName string `json:"employeeName" description:"员工名称"`
	Age          int    `json:"age"          description:"员工年纪"`
	DepartmentId int    `json:"departmentId" description:"员工部门ID"`
}
